package com.oneapi.config;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Test helper that creates isolated H2 in-memory databases in PostgreSQL compatibility mode.
 * <p>
 * The PostgreSQL-compatible URL is used so that the PostgreSQL-only production code can be
 * exercised without requiring a real PostgreSQL server. H2-specific tweaks:
 * <ul>
 *   <li>{@code DATABASE_TO_LOWER=TRUE} / {@code CASE_INSENSITIVE_IDENTIFIERS=TRUE} — make
 *       unquoted identifiers behave case-insensitively like PostgreSQL.</li>
 *   <li>{@code NON_KEYWORDS=MATCH} — {@code match} is a column name in virtual_models; H2 treats
 *       it as a keyword otherwise.</li>
 * </ul>
 */
public final class TestDatabaseConfig {

    private static final AtomicInteger COUNTER = new AtomicInteger(0);

    private static final String BASE_URL = "jdbc:h2:mem:%s;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=MATCH";

    private TestDatabaseConfig() {}

    /** Build a PostgreSQL-compatible H2 URL for the given database name. */
    public static String buildUrl(String dbName) {
        return String.format(BASE_URL, dbName);
    }

    /** Create a fresh H2 in-memory HikariCP pool with a unique database name. */
    public static HikariDataSource createDataSource() {
        String dbName = "oneapi_test_" + COUNTER.incrementAndGet();
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(buildUrl(dbName));
        config.setUsername("sa");
        config.setPassword("");
        config.setMaximumPoolSize(1);
        config.setConnectionTimeout(5000);
        return new HikariDataSource(config);
    }

    /**
     * Reset an identity column to {@code MAX(id) + 1} so that later auto-generated inserts do not
     * collide with rows that were inserted with explicit ids during test setup.
     * <p>
     * Assumes the column was created with {@code GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY}.
     */
    public static void resetIdentity(DataSource ds, String table, String column) throws SQLException {
        try (Connection conn = ds.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COALESCE(MAX(" + column + "), 0) + 1 FROM " + table)) {
            int next = rs.next() ? rs.getInt(1) : 1;
            stmt.execute("ALTER TABLE " + table + " ALTER COLUMN " + column + " RESTART WITH " + next);
        }
    }
}
